/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/financial/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_financial_accounts_get"];
        put?: never;
        /** Open Account */
        post: operations["open_account_financial_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_financial_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Account */
        patch: operations["rename_account_financial_accounts__account_id__patch"];
        trace?: never;
    };
    "/financial/accounts/{account_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Restate Balance
         * @description Correct what this account holds, without touching a single movement.
         *
         *     For the ordinary case of declaring an account and not knowing what it
         *     held before the alerts Finflow already has: open it at zero, then send
         *     the figure the bank shows today. The opening balance is solved backwards
         *     so the ledger still adds up to it, every movement keeps counting exactly
         *     once, and net worth follows from the corrected number.
         *
         *     PUT because the body carries the whole fact. Allowed on a closed account:
         *     correcting what was already there is not new money moving.
         */
        put: operations["restate_balance_financial_accounts__account_id__balance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/accounts/{account_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Account
         * @description Stop taking movements, keeping the history and the balance.
         *
         *     Not a delete: a closed account still explains past spending, and a
         *     paid-off loan closing at zero is exactly what should stay visible.
         */
        post: operations["close_account_financial_accounts__account_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/accounts/{account_id}/credit-limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Credit Limit
         * @description State or restate what this card may owe.
         *
         *     PUT rather than PATCH: the body carries the whole fact, and sending no
         *     limit clears it rather than leaving the old one in place.
         */
        put: operations["set_credit_limit_financial_accounts__account_id__credit_limit_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/accounts/{account_id}/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Instrument
         * @description Add another card or account number whose alerts belong here.
         *
         *     One real account emails as a debit card for purchases and as an account
         *     number for transfers. Linking is always the owner's call — inferring it
         *     would be guessing about somebody's money — and it adopts the movements
         *     already waiting under that key.
         */
        post: operations["link_instrument_financial_accounts__account_id__instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description What a client may send, so a form cannot offer what the API rejects.
         *
         *     Unauthenticated like the merchant catalogue beside it: this is the shape
         *     of the API, not anybody's data, and a client needs it to render the form
         *     that a session is created from.
         */
        get: operations["get_catalog_financial_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read History
         * @description How this money has moved month by month, and how this month compares.
         *
         *     Nothing here is stored or scheduled. Restating what an account holds
         *     solves its opening balance backwards, so the opening balance plus every
         *     movement up to an instant *is* the balance at that instant — history is a
         *     replay of the ledger rather than a snapshot table to keep in step.
         *
         *     So this is the current best reconstruction of the past, not a log of what
         *     was believed at the time: declaring an account today, or correcting a
         *     balance, changes what last March reports. That is the same property that
         *     makes adoption retroactive, and it is right.
         *
         *     The comparison is aligned by day of the month rather than by whole months.
         *     Against a finished previous month, a month three days old always reports
         *     spending down by most of it — true, and useless.
         */
        get: operations["read_history_financial_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Net Worth
         * @description Assets minus liabilities, one figure per currency held.
         *
         *     Empty for somebody who declared no accounts, which is an ordinary answer:
         *     they are watching what comes in and goes out, not a net position.
         */
        get: operations["get_net_worth_financial_net_worth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summarize Spending
         * @description What a period adds up to, broken down by month, category, merchant or
         *     account — and totalled per currency, never across them.
         *
         *     It takes the same filters as `/transactions`, so any bucket here can be
         *     opened as a list by repeating the query with the bucket's key. `timezone`
         *     only affects `month`, and it matters: a purchase at 8pm on the 31st falls
         *     in the next month once it is read in UTC.
         */
        get: operations["summarize_spending_financial_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Movements, newest first, each with the merchant behind its text.
         *
         *     `merchant_id` and `category` are Merchant's answer, so a movement whose
         *     counterparty nobody has resolved yet matches neither — it is unknown, not
         *     uncategorized. `from` is included and `to` is not, so two consecutive
         *     months can be asked for without one movement landing in both.
         */
        get: operations["list_transactions_financial_transactions_get"];
        put?: never;
        /**
         * Enter Transaction
         * @description Record money the bank never emailed about.
         *
         *     An automatic payment, cash, a transfer that produced no alert. The account
         *     is optional: somebody watching only what comes in and goes out has none.
         */
        post: operations["enter_transaction_financial_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/financial/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_financial_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Transaction */
        patch: operations["edit_transaction_financial_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Alive, and which deployment this is.
         *
         *     The environment is here because the only other way to tell two stacks
         *     apart is the URL, and a URL is exactly what gets pasted into the wrong
         *     command. Anything about to write — `scripts/smoke.py` above all — asks the
         *     deployment itself rather than trusting the env file it happened to load.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inbox
         * @description The caller's forwarding address, and who is currently approved to send
         *     to it. Whose inbox to read comes from the verified token, never from the
         *     request.
         */
        get: operations["get_inbox_identity_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Approved Senders
         * @description Replace who may send to the caller's forwarding address.
         *
         *     A full replacement, not a merge: the lists sent here become the whole
         *     approved set. Leave both empty and the address is approved for nobody —
         *     connected in the sense of existing, but reading nothing.
         */
        patch: operations["update_approved_senders_identity_inbox_patch"];
        trace?: never;
    };
    "/identity/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_identity_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The caller's own account, read from storage rather than from the token
         *     it arrived with: after a rename the token still carries the old name until
         *     the next login, and this endpoint is what the client trusts instead.
         */
        get: operations["me_identity_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Change the caller's name. Whose account is edited comes from the
         *     verified token, never from the request, so there is no id to pass and no
         *     one else's account to reach.
         *
         *     The access token in hand keeps its old `name` claim until it expires —
         *     it is a snapshot of issuing time, and this response is the current truth.
         */
        patch: operations["update_profile_identity_me_patch"];
        trace?: never;
    };
    "/identity/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and assign it a forwarding address.
         *
         *     The address itself never appears in this response — it depends only on
         *     the new account's id, so `GET /identity/inbox` right after this call
         *     already has it.
         */
        post: operations["register_identity_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description What this context's states are called, and what an instrument may be.
         */
        get: operations["get_catalog_ingestion_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description The caller's bank mail, newest first.
         *
         *     An empty list is an ordinary answer: it means nothing has been forwarded
         *     yet, or the forwarding rule is not doing what its owner thinks it is.
         */
        get: operations["list_notifications_ingestion_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setup
         * @description The caller's four steps, which of them are done, and what is next.
         */
        get: operations["get_setup_ingestion_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Merchants */
        get: operations["list_merchants_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description What a client may send, and what the words in a response mean.
         */
        get: operations["get_catalog_merchants_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description The category vocabulary, for a dropdown that cannot drift from it.
         */
        get: operations["list_categories_merchants_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Merchant */
        get: operations["get_merchant_merchants__merchant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Merchant
         * @description Rename a merchant, recategorize it, or both.
         *
         *     Either counts as reviewing it: a user who named a merchant has looked at
         *     what it is, so it leaves the review queue.
         */
        patch: operations["edit_merchant_merchants__merchant_id__patch"];
        trace?: never;
    };
    "/merchants/{merchant_id}/aliases/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Alias
         * @description Move one spelling to another merchant, and return the new parent.
         *
         *     The correction is permanent: from here on that spelling resolves by exact
         *     match, and no rule re-derives where it belongs.
         */
        post: operations["move_alias_merchants__merchant_id__aliases_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/aliases/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split Alias
         * @description Pull one spelling out into a merchant of its own, and return it.
         */
        post: operations["split_alias_merchants__merchant_id__aliases_split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Merchant
         * @description Accept a merchant as it stands, guessed children included.
         */
        post: operations["confirm_merchant_merchants__merchant_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Merchants
         * @description Fold one merchant into the one named in the path, which survives.
         */
        post: operations["merge_merchants_merchants__merchant_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenResponse */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires At */
            expires_at: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** User Id */
            user_id: string;
        };
        /**
         * AccountKind
         * @description What kind of account this is.
         *
         *     Explicit string values: the kind is persisted, so reordering the members
         *     must not rewrite anybody's data.
         * @enum {string}
         */
        AccountKind: "savings" | "checking" | "cash" | "investment" | "credit_card" | "loan" | "mortgage";
        /**
         * AccountKindOption
         * @description An account kind, and which side of net worth it lands on.
         *
         *     `category` is derived from the kind and never chosen, so a client can
         *     group the dropdown — and say "money you owe" against a balance — without
         *     duplicating the rule that decides it.
         */
        AccountKindOption: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** AccountListResponse */
        AccountListResponse: {
            /** Accounts */
            accounts: components["schemas"]["AccountResponse"][];
            /** Net Worth */
            net_worth: components["schemas"]["NetWorthResponse"][];
        };
        /** AccountResponse */
        AccountResponse: {
            /** Available */
            available: string | null;
            /** Balance */
            balance: string;
            /** Bank */
            bank: string | null;
            /** Category */
            category: string;
            /** Closed At */
            closed_at: number | null;
            /** Credit Limit */
            credit_limit: string | null;
            /** Currency */
            currency: string;
            /** Id */
            id: string;
            /** Instruments */
            instruments: string[];
            /** Kind */
            kind: string;
            /** Movements Applied */
            movements_applied: number;
            /** Name */
            name: string;
            /** Opened At */
            opened_at: number;
            /** Opening Balance */
            opening_balance: string;
        };
        /**
         * AccountScope
         * @enum {string}
         */
        AccountScope: "open" | "closed" | "all";
        /**
         * AliasResponse
         * @description One child: a spelling that resolves to this merchant.
         */
        AliasResponse: {
            /** Fingerprint */
            fingerprint: string;
            /** First Seen */
            first_seen: number;
            /** Last Seen */
            last_seen: number;
            /** Origin */
            origin: string;
            /** Raw Text */
            raw_text: string;
            /** Root Key */
            root_key: string;
            /** Times Seen */
            times_seen: number;
        };
        /**
         * CatalogOption
         * @description One admissible value, and something to put beside it in a dropdown.
         */
        CatalogOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** CategoryListResponse */
        CategoryListResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryResponse"][];
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "COP" | "USD";
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** User Id */
            user_id: string;
        };
        /** EditMerchantPayload */
        EditMerchantPayload: {
            category?: components["schemas"]["MerchantCategory"] | null;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * EditTransactionPayload
         * @description A correction. Everything omitted is left alone.
         *
         *     On a movement that came from a bank alert, the first correction keeps what
         *     the bank said: `stated` on the response is how a reader tells the two
         *     apart afterwards.
         */
        EditTransactionPayload: {
            /** Account Id */
            account_id?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Counterparty */
            counterparty?: string | null;
            currency?: components["schemas"]["Currency"] | null;
            /**
             * Detach
             * @default false
             */
            detach: boolean;
            /** Note */
            note?: string | null;
            /** Occurred At */
            occurred_at?: number | null;
        };
        /**
         * EnterTransactionPayload
         * @description Money that moved without an alert to announce it.
         */
        EnterTransactionPayload: {
            /** Account Id */
            account_id?: string | null;
            /** Amount */
            amount: number | string;
            /**
             * Bank
             * @default
             */
            bank: string;
            /** Counterparty */
            counterparty: string;
            /** @default COP */
            currency: components["schemas"]["Currency"];
            direction: components["schemas"]["MovementDirection"];
            /** Note */
            note?: string | null;
            /** Occurred At */
            occurred_at: number;
        };
        /**
         * FinancialCatalogResponse
         * @description Every vocabulary this context's endpoints accept.
         *
         *     `instrument_kinds` is the one that is not an account kind and is the one
         *     people reach for anyway: a savings account is `savings`, but the alerts it
         *     sends name the instrument `account`. Offer it as its own list, never a
         *     text field.
         */
        FinancialCatalogResponse: {
            /** Account Categories */
            account_categories: components["schemas"]["CatalogOption"][];
            /** Account Kinds */
            account_kinds: components["schemas"]["AccountKindOption"][];
            /** Account Scopes */
            account_scopes: components["schemas"]["CatalogOption"][];
            /** Currencies */
            currencies: components["schemas"]["CatalogOption"][];
            /** Instrument Kinds */
            instrument_kinds: components["schemas"]["CatalogOption"][];
            /** Movement Directions */
            movement_directions: components["schemas"]["CatalogOption"][];
            /** Summary Groupings */
            summary_groupings: components["schemas"]["CatalogOption"][];
            /** Transaction Origins */
            transaction_origins: components["schemas"]["CatalogOption"][];
            /** Transaction Statuses */
            transaction_statuses: components["schemas"]["CatalogOption"][];
        };
        /** FinancialHistoryResponse */
        FinancialHistoryResponse: {
            comparison: components["schemas"]["PeriodComparisonResponse"];
            /** Months */
            months: components["schemas"]["MonthlyPointResponse"][];
            /** Timezone */
            timezone: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InboxSendersPayload
         * @description The senders approved for the caller's one forwarding address.
         *
         *     No address here — it is assigned automatically and never chosen by a
         *     caller. Both lists may be empty, which approves nothing: a forwarding
         *     address with no approved sender reads nothing, the safe default rather
         *     than a broken one.
         */
        InboxSendersPayload: {
            /** Allowed Addresses */
            allowed_addresses?: string[];
            /** Allowed Domains */
            allowed_domains?: string[];
        };
        /** InboxSetupResponse */
        InboxSetupResponse: {
            /** Address */
            address: string;
            /** Current */
            current: string | null;
            /** Ready */
            ready: boolean;
            /** Steps */
            steps: components["schemas"]["SetupStepResponse"][];
            /** Unapproved Senders */
            unapproved_senders: string[];
        };
        /**
         * IngestionCatalogResponse
         * @description Ingestion's vocabulary, for the screens that render or filter by it.
         *
         *     `instrument_kinds` is the one a client sends rather than displays, and it
         *     is published from here rather than from Financial because these are the
         *     words a bank alert arrives with. An account declared with any other
         *     spelling is accepted and then never matches an alert — silently, since
         *     nothing about that is an error.
         */
        IngestionCatalogResponse: {
            /** Deferred Reasons */
            deferred_reasons: components["schemas"]["CatalogOption"][];
            /** Ignored Reasons */
            ignored_reasons: components["schemas"]["CatalogOption"][];
            /** Instrument Kinds */
            instrument_kinds: components["schemas"]["CatalogOption"][];
            /** Processing Statuses */
            processing_statuses: components["schemas"]["CatalogOption"][];
            /** Setup Steps */
            setup_steps: components["schemas"]["CatalogOption"][];
        };
        /**
         * InstrumentKind
         * @description The sort of card or account a movement arrived through.
         *
         *     Financial's own vocabulary, mapped at the boundary from whatever the
         *     publishing context calls its instruments — the same arrangement as
         *     `MovementDirection`. Neither context gets to change the other's meaning by
         *     editing its own.
         *
         *     Not the same thing as `AccountKind`, and the difference is the whole point
         *     of this type existing. `AccountKind` is what the owner calls the account;
         *     this is what the *bank* calls the thing the money moved through, and only
         *     these words ever appear in an alert. A savings account is declared
         *     `SAVINGS` and its transfers arrive as `ACCOUNT` — spelling the fingerprint
         *     with the account kind produces a key no alert can ever match, and the
         *     owner finds out only by noticing that nothing was ever assigned.
         * @enum {string}
         */
        InstrumentKind: "credit_card" | "debit_card" | "savings_account" | "checking_account" | "account";
        /**
         * LinkInstrumentPayload
         * @description Teach an account another of the names its alerts arrive under.
         *
         *     One real account emails as a debit card for purchases and as an account
         *     number for transfers, under different last four digits. Both have to be
         *     linked or half its movements wait forever.
         */
        LinkInstrumentPayload: {
            /** Bank */
            bank: string;
            instrument_kind: components["schemas"]["InstrumentKind"];
            /** Last Four */
            last_four: string;
        };
        /** LoginPayload */
        LoginPayload: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MerchantCatalogResponse
         * @description Every vocabulary this context's endpoints accept or return.
         *
         *     `categories` repeats what `GET /merchants/categories` already answers.
         *     That endpoint stays: it is what a client already calls, and one list in
         *     two places costs nothing next to breaking it.
         */
        MerchantCatalogResponse: {
            /** Alias Origins */
            alias_origins: components["schemas"]["CatalogOption"][];
            /** Categories */
            categories: components["schemas"]["CatalogOption"][];
            /** Counterparty Kinds */
            counterparty_kinds: components["schemas"]["CatalogOption"][];
            /** Sorts */
            sorts: components["schemas"]["CatalogOption"][];
            /** Statuses */
            statuses: components["schemas"]["CatalogOption"][];
        };
        /**
         * MerchantCategory
         * @description What kind of spending this merchant represents.
         *
         *     Explicit string values: the category is persisted and shown in a dropdown,
         *     so reordering the members must not rewrite anybody's data.
         * @enum {string}
         */
        MerchantCategory: "uncategorized" | "groceries" | "restaurants" | "transport" | "fuel" | "shopping" | "entertainment" | "subscriptions" | "utilities" | "health" | "education" | "travel" | "fees" | "transfers" | "income" | "other";
        /** MerchantDetailResponse */
        MerchantDetailResponse: {
            /** Alias Count */
            alias_count: number;
            /** Aliases */
            aliases: components["schemas"]["AliasResponse"][];
            /** Category */
            category: string;
            /** Display Name */
            display_name: string;
            /** First Seen */
            first_seen: number;
            /** Id */
            id: string;
            /** Last Seen */
            last_seen: number;
            /** Needs Review */
            needs_review: boolean;
            /** Status */
            status: string;
            /** Times Seen */
            times_seen: number;
        };
        /** MerchantListResponse */
        MerchantListResponse: {
            /** Limit */
            limit: number;
            /** Merchants */
            merchants: components["schemas"]["personal_finance__contexts__merchant__presentation__http__router__MerchantResponse"][];
            /** Needs Review */
            needs_review: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * MerchantSort
         * @enum {string}
         */
        MerchantSort: "name" | "last_seen" | "times_seen";
        /**
         * MergeMerchantsPayload
         * @description The merchant in the path survives and takes everything this one had.
         */
        MergeMerchantsPayload: {
            /** Absorbed Merchant Id */
            absorbed_merchant_id: string;
        };
        /** MonthlyPointResponse */
        MonthlyPointResponse: {
            /** Ends At */
            ends_at: number;
            /** Key */
            key: string;
            /** Net Worth */
            net_worth: components["schemas"]["NetWorthResponse"][];
            /** Partial */
            partial: boolean;
            /** Starts At */
            starts_at: number;
            /** Totals */
            totals: components["schemas"]["SpendingTotalsResponse"][];
        };
        /**
         * MoveAliasPayload
         * @description Reattach one child to a different parent.
         */
        MoveAliasPayload: {
            /** Fingerprint */
            fingerprint: string;
            /** Target Merchant Id */
            target_merchant_id: string;
        };
        /**
         * MovementDirection
         * @description Which way the money went, in Financial's own vocabulary.
         *
         *     Ingestion has an enum that happens to look identical today. Mapping
         *     between them at the boundary is the point: neither context gets to change
         *     the other's meaning by editing its own.
         * @enum {string}
         */
        MovementDirection: "outgoing" | "incoming";
        /** NetWorthResponse */
        NetWorthResponse: {
            /** Assets */
            assets: string;
            /** Currency */
            currency: string;
            /** Liabilities */
            liabilities: string;
            /** Total */
            total: string;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Limit */
            limit: number;
            /** Notifications */
            notifications: components["schemas"]["NotificationResponse"][];
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * NotificationResponse
         * @description One arrival. No body: a list never shows the email itself, and two of
         *     the states below discarded theirs on purpose.
         */
        NotificationResponse: {
            /** Deferred Reason */
            deferred_reason: string | null;
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Received At */
            received_at: number;
            /** Sender */
            sender: string;
            /** Status */
            status: string;
            /** Subject */
            subject: string;
        };
        /**
         * OpenAccountPayload
         * @description Declare an account.
         *
         *     Give it an instrument and every alert arriving under that bank and those
         *     last four digits lands here — including the ones that already arrived and
         *     have been waiting. Leave it out for what never emails: cash, a mortgage.
         */
        OpenAccountPayload: {
            /** Bank */
            bank?: string | null;
            /** Credit Limit */
            credit_limit?: number | string | null;
            /** @default COP */
            currency: components["schemas"]["Currency"];
            instrument_kind?: components["schemas"]["InstrumentKind"] | null;
            kind: components["schemas"]["AccountKind"];
            /** Last Four */
            last_four?: string | null;
            /** Name */
            name: string;
            /** Opening Balance */
            opening_balance?: number | string | null;
        };
        /**
         * PeriodComparisonResponse
         * @description This month so far against the same stretch of the month before it.
         *
         *     Aligned by day of the month: on the 15th, the 1st to the 15th against the
         *     1st to the 15th. Comparing a young month against a finished one reports
         *     spending down by most of it, every month, and is right about nothing.
         */
        PeriodComparisonResponse: {
            /** Clamped */
            clamped: boolean;
            /** Key */
            key: string;
            /** Net Worth */
            net_worth: components["schemas"]["NetWorthResponse"][];
            /** Previous Key */
            previous_key: string;
            /** Previous Net Worth */
            previous_net_worth: components["schemas"]["NetWorthResponse"][];
            /** Previous Starts At */
            previous_starts_at: number;
            /** Previous Through */
            previous_through: number;
            /** Previous Totals */
            previous_totals: components["schemas"]["SpendingTotalsResponse"][];
            /** Starts At */
            starts_at: number;
            /** Through */
            through: number;
            /** Totals */
            totals: components["schemas"]["SpendingTotalsResponse"][];
        };
        /**
         * ProcessingStatus
         * @description Explicit string values: this enum is persisted and serialized, so the
         *     stored representation must survive a reordering of the members.
         * @enum {string}
         */
        ProcessingStatus: "received" | "queued" | "processing" | "processed" | "pending_fallback" | "failed" | "ignored";
        /**
         * RegisterPayload
         * @description Registration, plus the same optional sender approval `PATCH
         *     /identity/inbox` accepts — set here to skip a second call, or leave
         *     empty and approve senders later. The forwarding address itself is
         *     assigned regardless of whether any sender is named here.
         */
        RegisterPayload: {
            /** Allowed Addresses */
            allowed_addresses?: string[];
            /** Allowed Domains */
            allowed_domains?: string[];
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Password */
            password: string;
        };
        /** RegisteredInboxResponse */
        RegisteredInboxResponse: {
            /** Address */
            address: string;
            /** Allowed Addresses */
            allowed_addresses: string[];
            /** Allowed Domains */
            allowed_domains: string[];
        };
        /** RenameAccountPayload */
        RenameAccountPayload: {
            /** Name */
            name: string;
        };
        /**
         * RestateBalancePayload
         * @description What the account holds **now** — the figure the bank shows today.
         *
         *     Not the opening balance: that one is derived from this and the movements
         *     already recorded, because it is the half nobody can look up. Signed, so
         *     an overdrawn account and an overpaid card can both be stated.
         */
        RestateBalancePayload: {
            /** Balance */
            balance: number | string;
        };
        /**
         * SetCreditLimitPayload
         * @description State or restate what a card may owe. `null` clears it.
         */
        SetCreditLimitPayload: {
            /** Credit Limit */
            credit_limit?: number | string | null;
        };
        /**
         * SetupStepResponse
         * @description One step of connecting a bank.
         *
         *     `at` is null for the two steps that are states rather than events (the
         *     address exists, somebody is approved) — and for any step still open.
         */
        SetupStepResponse: {
            /** At */
            at: number | null;
            /** Done */
            done: boolean;
            /** Key */
            key: string;
        };
        /** SpendingSummaryResponse */
        SpendingSummaryResponse: {
            /** Group By */
            group_by: string;
            /** Groups */
            groups: components["schemas"]["SummaryGroupResponse"][];
            /** Timezone */
            timezone: string;
            /** Totals */
            totals: components["schemas"]["SpendingTotalsResponse"][];
        };
        /** SpendingTotalsResponse */
        SpendingTotalsResponse: {
            /** Currency */
            currency: string;
            /** Incoming */
            incoming: string;
            /** Movements */
            movements: number;
            /** Net */
            net: string;
            /** Outgoing */
            outgoing: string;
        };
        /**
         * SplitAliasPayload
         * @description Pull one child out into a merchant of its own.
         */
        SplitAliasPayload: {
            category?: components["schemas"]["MerchantCategory"] | null;
            /** Display Name */
            display_name?: string | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /**
         * StatedResponse
         * @description What the bank said, before anybody corrected it.
         */
        StatedResponse: {
            /** Amount */
            amount: string;
            /** Counterparty */
            counterparty: string;
            /** Currency */
            currency: string;
            /** Occurred At */
            occurred_at: number;
        };
        /** SummaryGroupResponse */
        SummaryGroupResponse: {
            /** Key */
            key: string | null;
            /** Label */
            label: string;
            /** Movements */
            movements: number;
            /** Totals */
            totals: components["schemas"]["SpendingTotalsResponse"][];
        };
        /**
         * SummaryGrouping
         * @description Which question a summary answers.
         * @enum {string}
         */
        SummaryGrouping: "month" | "category" | "merchant" | "account";
        /** TransactionListResponse */
        TransactionListResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /**
         * TransactionOrigin
         * @description Where a movement came from, which decides what may be trusted about it.
         *
         *     A bank alert states a fact somebody else recorded; a manual entry is the
         *     user's own claim. Automatic payments that never email are exactly why the
         *     second exists.
         * @enum {string}
         */
        TransactionOrigin: "bank_alert" | "manual";
        /** TransactionResponse */
        TransactionResponse: {
            /** Account Id */
            account_id: string | null;
            /** Amount */
            amount: string;
            /** Bank */
            bank: string;
            /** Counterparty */
            counterparty: string;
            /** Currency */
            currency: string;
            /** Direction */
            direction: string;
            /** Id */
            id: string;
            merchant: components["schemas"]["personal_finance__contexts__financial__presentation__http__router__MerchantResponse"] | null;
            /** Note */
            note: string | null;
            /** Occurred At */
            occurred_at: number;
            /** Origin */
            origin: string;
            stated: components["schemas"]["StatedResponse"] | null;
            /** Status */
            status: string;
        };
        /**
         * UpdateProfilePayload
         * @description Only the name: the email is the account's identity, not a field.
         */
        UpdateProfilePayload: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * MerchantResponse
         * @description The canonical merchant behind this movement's counterparty text.
         *
         *     Joined when the answer is read, never stored on the movement: the grouping
         *     belongs to Merchant and a user can change it, so a rename or a merge shows
         *     up on every past movement at once with nothing to re-process.
         */
        personal_finance__contexts__financial__presentation__http__router__MerchantResponse: {
            /** Category */
            category: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Needs Review */
            needs_review: boolean;
        };
        /** MerchantResponse */
        personal_finance__contexts__merchant__presentation__http__router__MerchantResponse: {
            /** Alias Count */
            alias_count: number;
            /** Category */
            category: string;
            /** Display Name */
            display_name: string;
            /** First Seen */
            first_seen: number;
            /** Id */
            id: string;
            /** Last Seen */
            last_seen: number;
            /** Needs Review */
            needs_review: boolean;
            /** Status */
            status: string;
            /** Times Seen */
            times_seen: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_financial_accounts_get: {
        parameters: {
            query?: {
                scope?: components["schemas"]["AccountScope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_account_financial_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAccountPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_financial_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_account_financial_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameAccountPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restate_balance_financial_accounts__account_id__balance_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestateBalancePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_account_financial_accounts__account_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_credit_limit_financial_accounts__account_id__credit_limit_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCreditLimitPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_instrument_financial_accounts__account_id__instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkInstrumentPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_financial_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialCatalogResponse"];
                };
            };
        };
    };
    read_history_financial_history_get: {
        parameters: {
            query?: {
                months?: number;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_net_worth_financial_net_worth_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthResponse"][];
                };
            };
        };
    };
    summarize_spending_financial_summary_get: {
        parameters: {
            query?: {
                group_by?: components["schemas"]["SummaryGrouping"];
                from?: number | null;
                to?: number | null;
                account_id?: string | null;
                unassigned?: boolean | null;
                origin?: components["schemas"]["TransactionOrigin"] | null;
                direction?: components["schemas"]["MovementDirection"] | null;
                search?: string | null;
                merchant_id?: string | null;
                category?: string | null;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_financial_transactions_get: {
        parameters: {
            query?: {
                account_id?: string | null;
                unassigned?: boolean | null;
                origin?: components["schemas"]["TransactionOrigin"] | null;
                direction?: components["schemas"]["MovementDirection"] | null;
                search?: string | null;
                merchant_id?: string | null;
                category?: string | null;
                from?: number | null;
                to?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enter_transaction_financial_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnterTransactionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_financial_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_transaction_financial_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTransactionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_inbox_identity_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredInboxResponse"];
                };
            };
        };
    };
    update_approved_senders_identity_inbox_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxSendersPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredInboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_identity_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_identity_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    update_profile_identity_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfilePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_identity_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_ingestion_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionCatalogResponse"];
                };
            };
        };
    };
    list_notifications_ingestion_notifications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProcessingStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setup_ingestion_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSetupResponse"];
                };
            };
        };
    };
    list_merchants_merchants_get: {
        parameters: {
            query?: {
                search?: string | null;
                category?: components["schemas"]["MerchantCategory"] | null;
                needs_review?: boolean | null;
                sort?: components["schemas"]["MerchantSort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_merchants_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantCatalogResponse"];
                };
            };
        };
    };
    list_categories_merchants_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
    get_merchant_merchants__merchant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_merchant_merchants__merchant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditMerchantPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_alias_merchants__merchant_id__aliases_move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveAliasPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_alias_merchants__merchant_id__aliases_split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitAliasPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_merchant_merchants__merchant_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_merchants_merchants__merchant_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeMerchantsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
