/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConectarRouteImport } from './routes/conectar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as CuentasIndexRouteImport } from './routes/cuentas/index'
import { Route as CuentasNuevaRouteImport } from './routes/cuentas/nueva'
import { Route as GuiasIndexRouteImport } from './routes/guias/index'
import { Route as GuiasCuentasYMovimientosRouteImport } from './routes/guias/cuentas-y-movimientos'
import { Route as TransaccionesIndexRouteImport } from './routes/transacciones/index'
import { Route as TransaccionesTransactionIdRouteImport } from './routes/transacciones/$transactionId'
import { Route as TransaccionesNuevaRouteImport } from './routes/transacciones/nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarRoute = ConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasIndexRoute = CuentasIndexRouteImport.update({
  id: '/cuentas/',
  path: '/cuentas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasNuevaRoute = CuentasNuevaRouteImport.update({
  id: '/cuentas/nueva',
  path: '/cuentas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasCuentasYMovimientosRoute =
  GuiasCuentasYMovimientosRouteImport.update({
    id: '/guias/cuentas-y-movimientos',
    path: '/guias/cuentas-y-movimientos',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransaccionesIndexRoute = TransaccionesIndexRouteImport.update({
  id: '/transacciones/',
  path: '/transacciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaccionesTransactionIdRoute =
  TransaccionesTransactionIdRouteImport.update({
    id: '/transacciones/$transactionId',
    path: '/transacciones/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransaccionesNuevaRoute = TransaccionesNuevaRouteImport.update({
  id: '/transacciones/nueva',
  path: '/transacciones/nueva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conectar': typeof ConectarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/cuentas/nueva': typeof CuentasNuevaRoute
  '/guias/cuentas-y-movimientos': typeof GuiasCuentasYMovimientosRoute
  '/transacciones/$transactionId': typeof TransaccionesTransactionIdRoute
  '/transacciones/nueva': typeof TransaccionesNuevaRoute
  '/cuentas/': typeof CuentasIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/transacciones/': typeof TransaccionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conectar': typeof ConectarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/cuentas/nueva': typeof CuentasNuevaRoute
  '/guias/cuentas-y-movimientos': typeof GuiasCuentasYMovimientosRoute
  '/transacciones/$transactionId': typeof TransaccionesTransactionIdRoute
  '/transacciones/nueva': typeof TransaccionesNuevaRoute
  '/cuentas': typeof CuentasIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/transacciones': typeof TransaccionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conectar': typeof ConectarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/cuentas/nueva': typeof CuentasNuevaRoute
  '/guias/cuentas-y-movimientos': typeof GuiasCuentasYMovimientosRoute
  '/transacciones/$transactionId': typeof TransaccionesTransactionIdRoute
  '/transacciones/nueva': typeof TransaccionesNuevaRoute
  '/cuentas/': typeof CuentasIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/transacciones/': typeof TransaccionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conectar'
    | '/login'
    | '/perfil'
    | '/cuentas/nueva'
    | '/guias/cuentas-y-movimientos'
    | '/transacciones/$transactionId'
    | '/transacciones/nueva'
    | '/cuentas/'
    | '/guias/'
    | '/transacciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conectar'
    | '/login'
    | '/perfil'
    | '/cuentas/nueva'
    | '/guias/cuentas-y-movimientos'
    | '/transacciones/$transactionId'
    | '/transacciones/nueva'
    | '/cuentas'
    | '/guias'
    | '/transacciones'
  id:
    | '__root__'
    | '/'
    | '/conectar'
    | '/login'
    | '/perfil'
    | '/cuentas/nueva'
    | '/guias/cuentas-y-movimientos'
    | '/transacciones/$transactionId'
    | '/transacciones/nueva'
    | '/cuentas/'
    | '/guias/'
    | '/transacciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConectarRoute: typeof ConectarRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  CuentasNuevaRoute: typeof CuentasNuevaRoute
  GuiasCuentasYMovimientosRoute: typeof GuiasCuentasYMovimientosRoute
  TransaccionesTransactionIdRoute: typeof TransaccionesTransactionIdRoute
  TransaccionesNuevaRoute: typeof TransaccionesNuevaRoute
  CuentasIndexRoute: typeof CuentasIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  TransaccionesIndexRoute: typeof TransaccionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar': {
      id: '/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof ConectarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas/': {
      id: '/cuentas/'
      path: '/cuentas'
      fullPath: '/cuentas/'
      preLoaderRoute: typeof CuentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas/nueva': {
      id: '/cuentas/nueva'
      path: '/cuentas/nueva'
      fullPath: '/cuentas/nueva'
      preLoaderRoute: typeof CuentasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/cuentas-y-movimientos': {
      id: '/guias/cuentas-y-movimientos'
      path: '/guias/cuentas-y-movimientos'
      fullPath: '/guias/cuentas-y-movimientos'
      preLoaderRoute: typeof GuiasCuentasYMovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacciones/': {
      id: '/transacciones/'
      path: '/transacciones'
      fullPath: '/transacciones/'
      preLoaderRoute: typeof TransaccionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacciones/$transactionId': {
      id: '/transacciones/$transactionId'
      path: '/transacciones/$transactionId'
      fullPath: '/transacciones/$transactionId'
      preLoaderRoute: typeof TransaccionesTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacciones/nueva': {
      id: '/transacciones/nueva'
      path: '/transacciones/nueva'
      fullPath: '/transacciones/nueva'
      preLoaderRoute: typeof TransaccionesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConectarRoute: ConectarRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  CuentasNuevaRoute: CuentasNuevaRoute,
  GuiasCuentasYMovimientosRoute: GuiasCuentasYMovimientosRoute,
  TransaccionesTransactionIdRoute: TransaccionesTransactionIdRoute,
  TransaccionesNuevaRoute: TransaccionesNuevaRoute,
  CuentasIndexRoute: CuentasIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  TransaccionesIndexRoute: TransaccionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
